export enum PERMISSIONS {
  //DASHBOARD
  'DASHBOARD_READ'='DASHBOARD_READ',
  'DASHBOARD_UPDATE'='DASHBOARD_UPDATE',
  'DASHBOARD_CREATE'='DASHBOARD_CREATE',
  'DASHBOARD_DELETE'='DASHBOARD_DELETE',
  'DASHBOARD_PERMANENT_DELETE'='DASHBOARD_PERMANENT_DELETE',

};

export enum ROLES{
  SYSTEM_USER = "System User",
  RAE_SUPER_ADMIN = "RAE Super Admin",
  RAE_RESEARCH_ADMIN = "RAE Research Admin",
  CUSTOMER_ADMIN = "Customer Admin",
  ORGANIZATION_ADMIN = "Organization Admin",
  LOCATION_ADMIN = "Location Admin",
  CASE_MANAGER = "Case Manager",
  ORDERING_PROVIDER = "Ordering Provider",
  CLINICAL_STAFF = "Clinical Staff",
  PEER_PORTAL_USER = "Peer Portal User",
  APP_USER = "App User",
}

